services:
  web:
    build: .
    container_name: rivyou_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=True
    restart: always
