# Generated by Django 6.0.6 on 2026-06-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["product_name"]},
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_categor_14b9c0_idx",
        ),
    ]
